# Generated by Django 5.1.5 on 2025-01-18 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "mbid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "mbid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("artist_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="artists", to="recommender.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "mbid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="releases", to="recommender.artist"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="releases", to="recommender.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "mbid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("number", models.CharField(blank=True, max_length=10, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "recording_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "recording_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="tracks", to="recommender.genre"
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="recommender.release",
                    ),
                ),
            ],
        ),
    ]
