# Generated by Django 5.1.5 on 2025-01-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="lyrics",
            field=models.TextField(blank=True, null=True),
        ),
    ]
