# Generated by Django 5.1.5 on 2025-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0002_track_lyrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="country",
        ),
        migrations.AddField(
            model_name="release",
            name="rg_mbid",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
