# Generated by Django 5.1.5 on 2025-01-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_remove_release_country_release_rg_mbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
